pub mod algorithm;
pub mod bar;
pub mod broker;
pub mod commission;
pub mod consolidator;
pub mod context;
pub mod data;
pub mod engine;
pub mod indicators;
pub mod slice;
pub mod slippage;
pub mod stats;

pub use algorithm::Algorithm;
pub use commission::{CommissionModel, NoCommission, PerShareCommission, PercentCommission};
pub use context::Context;
pub use engine::{run, run_backtest, BacktestResult};
pub use slice::Slice;
pub use slippage::{FillContext, FixedSlippage, NoSlippage, PercentSlippage, SlippageModel};
pub use stats::{BacktestStats, EquityPoint, Trade};
